[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@uniswap/v4-core/=lib/v4-core",
    "@uniswap/v4-periphery/=lib/v4-periphery",
    "solmate/=lib/solmate/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
